kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
featureGates:
  "PodDefaultNetwork": true
networking:
  disableDefaultCNI: false

nodes:
  - role: control-plane
    image: nonnetwork-pods-node:dev
  - role: worker
    image: nonnetwork-pods-node:dev